// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read values from Vite environment variables so the endpoint can be swapped
// between the real Supabase host and a proxy (e.g. JioBase) without touching
// the code. Ensure these are set in `.env` or in your deployment provider.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL) {
  throw new Error('Missing environment variable VITE_SUPABASE_URL');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing environment variable VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});